### ISSUE TITLE
Cannot generate a developer API Key?

### ISSUE THREAD

**Issue by denislam** [0x15f/coinschedule-php#1]
Is the developer API key site working? The create button seems disabled. https://developers.coinschedule.com/portal/dashboard.php?page=keys

**Comment by 0x15f** [comment]
Hi @denislam ,

The API isn't production ready so key generation has been disabled. We expect to publicly release within the coming weeks.

**Comment by 0x15f** [comment]
@denislam you can get an API key from the docs page.
